from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path

from compiler import CoverageTemplateCompiler
from research_profiles import research_profiles


ROOT = Path(__file__).resolve().parents[3]
OUTPUT = ROOT / "packages" / "nollm-core" / "src" / "nollm_core" / "compiled_templates.py"
DIRECTIONS = ("coverage_up", "coverage_down", "lateral")


def canonical_document() -> bytes:
    compiler = CoverageTemplateCompiler()
    document = {
        "schema_version": "nollm_compiled_geometry_templates_v1",
        "templates": [
            compiler.compile(profile.profile_id, direction).to_mapping()
            for profile in research_profiles()
            for direction in DIRECTIONS
        ],
    }
    return json.dumps(document, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8") + b"\n"


def render(payload: bytes) -> str:
    digest = sha256(payload).hexdigest()
    return (
        '"""Generated by lab/nollm-lab/geometry/generate_compiled_templates.py."""\n\n'
        f"COMPILED_TEMPLATES_SHA256 = {digest!r}\n"
        f"COMPILED_TEMPLATES_JSON = {payload!r}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(canonical_document())
    digest = sha256(canonical_document()).hexdigest()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("compiled geometry template artifact is stale")
        print(f"artifact SHA-256: {digest}")
        return
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}; artifact SHA-256: {digest}")


if __name__ == "__main__":
    main()
