from __future__ import annotations

from hashlib import sha256
import json
from pathlib import Path

from compiler import CoverageTemplateCompiler
from nollm_core.profiles import profiles


ROOT = Path(__file__).resolve().parents[3]
OUTPUT = ROOT / "packages" / "nollm-core" / "src" / "nollm_core" / "compiled_templates.py"
DIRECTIONS = ("coverage_up", "coverage_down", "lateral")


def canonical_document() -> bytes:
    compiler = CoverageTemplateCompiler()
    document = {
        "schema_version": "nollm_compiled_geometry_templates_v1",
        "templates": [
            compiler.compile(profile.profile_id, direction).to_mapping()
            for profile in profiles()
            for direction in DIRECTIONS
        ],
    }
    return json.dumps(document, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8") + b"\n"


def render(payload: bytes) -> str:
    digest = sha256(payload).hexdigest()
    return (
        '"""Generated by lab/nollm-lab/geometry/generate_compiled_templates.py."""\n\n'
        f"COMPILED_TEMPLATES_SHA256 = {digest!r}\n"
        f"COMPILED_TEMPLATES_JSON = {payload!r}\n"
    )


def main() -> None:
    rendered = render(canonical_document())
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
