"""DC1 Cortex Compiler deterministic baseline report generator."""

from __future__ import annotations

import argparse
import platform
import tempfile
from pathlib import Path

from nollm.dream_geometry.cortex import DC1Rejection, compile_query
from nollm.dream_geometry.cortex.store import open_store as open_cortex_store
from nollm.dream_geometry.evidence import DreamShard, InterpretationRecord, OriginDescriptor, TemporalContext
from nollm.dream_geometry.evidence import open_store as open_evidence_store
from nollm.dream_geometry.protocol.contracts import InterpretationAuthoringMode, InterpretationKind, OriginKind, UsageState


def build_report() -> str:
    with tempfile.TemporaryDirectory(prefix="dc1-report-") as directory:
        results = _run_fixtures(Path(directory))
    lines = [
        "# DC1 Cortex Compiler Baseline Report",
        "",
        "Generated by `python -m nollm.dream_geometry.validation.dc1_cortex_report`.",
        "",
        "## Execution",
        "",
        f"- Python: `{platform.python_version()}`",
        "- contract_version: `dc1.v1`",
        "- fixture_data: `synthetic_only`",
        "- third_party_dependencies: `none`",
        "",
        "## Fixture Results",
        "",
        "| fixture | result |",
        "|---|---|",
    ]
    for name, result in results:
        lines.append(f"| {name} | {result} |")
    lines.extend(
        [
            "",
            "## Known Limits",
            "",
            "- DC1 does not prove natural-language understanding, rule truth, rule authority, Geometry placement, Field propagation, Recall quality, runtime integration, or security authenticity.",
            "- Growth budget schema is `max_axes`, `max_total_steps`, `max_ray_steps` with hard caps `8/48/16`.",
            "- Query budget schema is `max_axes`, `max_charts`, `max_layers`, `max_cells_per_layer` with hard caps `8/64/64/256`.",
            "- Relative-time Query requires at least one exact `explicit_in_query` text span and preserves caller text without absolute-time resolution.",
            "- `possible_conflict_refs` are checked only as explicit DE1 DreamShard or InterpretationRecord pointers; DC1 performs no conflict judgment.",
            "- Reopen validates compiled proposal semantics and receipt input snapshot / submitted fingerprint / normalized proposal consistency.",
            "- Same `rule_id` must keep one `(rule_version, rule_label, source_ref)` identity within a proposal.",
            "- Fingerprints are deterministic equivalence keys for idempotency and report recomputation only.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_report(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_report(), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the DC1 Cortex Compiler baseline report.")
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)
    write_report(Path(args.output))
    return 0


def _run_fixtures(root: Path) -> tuple[tuple[str, str], ...]:
    evidence = _fixture_store(root / "evidence")
    cortex = open_cortex_store(root / "cortex", evidence)
    accepted = cortex.compile_growth(_growth_payload()).proposal.proposal_id == "gp_kunming_growth_v1"
    retry = cortex.compile_growth(_growth_payload()).idempotent
    query_before = _tree_digest(root / "cortex")
    query = compile_query(_query_payload())
    query_zero_persistence = query.ephemeral and _tree_digest(root / "cortex") == query_before
    mismatch = _raises_code(lambda: cortex.compile_growth(_bad_explicit_payload()), "DC1_INVALID_TEXT_SPAN")
    memory_query = _raises_code(lambda: compile_query(_bad_query_memory_basis()), "DC1_QUERY_MEMORY_BASIS_FORBIDDEN")
    reopened = open_cortex_store(root / "cortex", evidence).get_growth_proposal("gp_kunming_growth_v1").subject_shard_id == "shard:rain"
    return (
        ("synthetic DreamShard fixture", "pass"),
        ("growth accepted with basis refs", "pass" if accepted else "fail"),
        ("growth idempotent retry", "pass" if retry else "fail"),
        ("query ephemeral zero persistence", "pass" if query_zero_persistence else "fail"),
        ("explicit span mismatch rejected", "pass" if mismatch else "fail"),
        ("query memory basis rejected", "pass" if memory_query else "fail"),
        ("cortex reopen validates proposal receipt", "pass" if reopened else "fail"),
        ("sealed path diff summary", "not run by report; covered by delivery validation"),
    )


def _fixture_store(root: Path):
    store = open_evidence_store(root)
    store.put_dream_shard(_shard("shard:rain", "昆明于2026年6月29日下雨了。"))
    store.put_dream_shard(_shard("shard:city", "昆明是中国云南省的城市。"))
    store.put_dream_shard(_shard("shard:revision", "2026年6月29日的天气记录仅适用于该日。"))
    store.put_interpretation(
        InterpretationRecord(
            "interpretation:city-note",
            "shard:city",
            InterpretationKind.classification,
            "城市 classification note",
            InterpretationAuthoringMode.llm_proposed,
            (),
            (),
            UsageState.tentative,
        )
    )
    return store


def _shard(shard_id: str, content: str) -> DreamShard:
    return DreamShard(shard_id, content, OriginDescriptor(OriginKind.user_utterance, "synthetic", "dc1", "user"), TemporalContext("2026-06-29T08:00:00+08:00", None, None, "zh-CN"), (), UsageState.tentative)


def _growth_payload() -> dict:
    return {
        "contract_version": "dc1.v1",
        "proposal_id": "gp_kunming_growth_v1",
        "subject_shard_id": "shard:rain",
        "submitted_at": "2026-06-29T08:30:00+08:00",
        "budget": {"max_axes": 4, "max_total_steps": 8, "max_ray_steps": 4},
        "do_not_infer": ["do not infer city classification from rain sentence"],
        "forbidden_inferences": ["do not infer current weather"],
        "possible_conflict_refs": ["interpretation:city-note"],
        "axes": [
            {"axis_id": "location", "ray": [{"step_id": "step_kunming", "expression": "昆明", "basis": "explicit_in_shard", "basis_refs": [{"ref_type": "text_span", "record_id": "shard:rain", "start_char": 0, "end_char": 2, "quoted_text": "昆明"}]}]},
            {"axis_id": "relation", "ray": [{"step_id": "step_city", "expression": "城市", "basis": "backed_by_other_shard", "basis_refs": [{"ref_type": "text_span", "record_id": "shard:city", "start_char": 9, "end_char": 11, "quoted_text": "城市"}]}]},
            {
                "axis_id": "absolute_time",
                "ray": [
                    {"step_id": "step_day", "expression": "2026年6月29日", "basis": "explicit_in_shard", "basis_refs": [{"ref_type": "text_span", "record_id": "shard:rain", "start_char": 3, "end_char": 13, "quoted_text": "2026年6月29日"}]},
                    {"step_id": "step_month", "expression": "2026年6月", "basis": "deterministic_projection", "basis_refs": [{"ref_type": "rule", "rule_id": "rule_date_projection", "rule_version": "v1", "rule_label": "date projection", "source_ref": "project:dc1"}, {"ref_type": "step", "input_step_id": "step_day"}]},
                    {"step_id": "step_year", "expression": "2026年", "basis": "deterministic_projection", "basis_refs": [{"ref_type": "rule", "rule_id": "rule_date_projection", "rule_version": "v1", "rule_label": "date projection", "source_ref": "project:dc1"}, {"ref_type": "step", "input_step_id": "step_month"}]},
                ],
            },
            {
                "axis_id": "phenomenon",
                "ray": [
                    {"step_id": "step_rain", "expression": "下雨", "basis": "explicit_in_shard", "basis_refs": [{"ref_type": "text_span", "record_id": "shard:rain", "start_char": 13, "end_char": 15, "quoted_text": "下雨"}]},
                    {"step_id": "step_precip", "expression": "降雨", "basis": "source_backed_rule", "basis_refs": [{"ref_type": "rule", "rule_id": "rule_weather_vocab", "rule_version": "v1", "rule_label": "weather vocabulary mapping", "source_ref": "project:weather"}]},
                    {"step_id": "step_weather", "expression": "天气现象", "basis": "provisional_llm_generalization", "basis_refs": [{"ref_type": "step", "input_step_id": "step_precip"}], "rationale": "external caller supplied candidate generalization"},
                ],
            },
        ],
    }


def _bad_explicit_payload() -> dict:
    payload = _growth_payload()
    payload["proposal_id"] = "gp_bad_explicit"
    payload["axes"] = [{"axis_id": "location", "ray": [{"step_id": "step_bad", "expression": "城市", "basis": "explicit_in_shard", "basis_refs": [{"ref_type": "text_span", "record_id": "shard:rain", "start_char": 0, "end_char": 2, "quoted_text": "城市"}]}]}]
    return payload


def _query_payload() -> dict:
    return {
        "contract_version": "dc1.v1",
        "probe_id": "probe_kunming_yesterday",
        "query_text": "昆明昨天是否下雨？",
        "reference_instant": "2026-06-30T09:00:00+08:00",
        "requires_runtime_resolution": True,
        "ephemeral": True,
        "budget": {"max_axes": 3, "max_charts": 64, "max_layers": 64, "max_cells_per_layer": 256},
        "do_not_infer": ["do not resolve relative time in compiler"],
        "forbidden_inferences": ["do not search memory while compiling query"],
        "axes": [
            {"axis_id": "location", "ray": [{"step_id": "step_q_kunming", "expression": "昆明", "basis": "explicit_in_query", "basis_refs": [{"ref_type": "text_span", "record_id": "probe_kunming_yesterday", "start_char": 0, "end_char": 2, "quoted_text": "昆明"}]}]},
            {"axis_id": "relative_time", "ray": [{"step_id": "step_q_yesterday", "expression": "昨天", "basis": "explicit_in_query", "basis_refs": [{"ref_type": "text_span", "record_id": "probe_kunming_yesterday", "start_char": 2, "end_char": 4, "quoted_text": "昨天"}]}]},
            {"axis_id": "phenomenon", "ray": [{"step_id": "step_q_rain", "expression": "下雨", "basis": "explicit_in_query", "basis_refs": [{"ref_type": "text_span", "record_id": "probe_kunming_yesterday", "start_char": 6, "end_char": 8, "quoted_text": "下雨"}]}]},
        ],
    }


def _bad_query_memory_basis() -> dict:
    payload = _query_payload()
    payload["axes"][0]["ray"][0]["basis"] = "explicit_in_shard"
    return payload


def _tree_digest(root: Path) -> tuple[tuple[str, str], ...]:
    if not root.exists():
        return ()
    return tuple(sorted((str(path.relative_to(root)), path.read_text(encoding="utf-8")) for path in root.rglob("*") if path.is_file()))


def _raises_code(callback, code: str) -> bool:
    try:
        callback()
    except DC1Rejection as exc:
        return code in exc.reason_codes
    return False


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["build_report", "main", "write_report"]
