"""DE1 Memory Substrate baseline report generator."""

from __future__ import annotations

import argparse
import json
import platform
import tempfile
from hashlib import sha256
from pathlib import Path

from nollm.dream_geometry.evidence import (
    FORMAT_VERSION,
    DreamShard,
    InterpretationRecord,
    OriginDescriptor,
    RevisionEdge,
    RevisionThread,
    TemporalContext,
    UsageStateTransition,
    canonical_json,
    open_store,
)
from nollm.dream_geometry.evidence.store import MemorySubstrateStore
from nollm.dream_geometry.protocol.contracts import (
    InterpretationAuthoringMode,
    InterpretationKind,
    OriginKind,
    RevisionRelation,
    UsageState,
)


def build_report() -> str:
    with tempfile.TemporaryDirectory(prefix="de1-report-") as directory:
        fixtures = _run_fixtures(Path(directory))
    lines = [
        "# DE1 Memory Substrate Baseline Report",
        "",
        "Generated by `python -m nollm.dream_geometry.validation.de1_memory_substrate_report`.",
        "",
        "## Execution",
        "",
        f"- Python: `{platform.python_version()}`",
        f"- format_version: `{FORMAT_VERSION}`",
        "- fixture_data: `synthetic_only`",
        "- third_party_dependencies: `none`",
        "",
        "## Fixture Results",
        "",
        "| fixture | result |",
        "|---|---|",
    ]
    for name, result in fixtures["results"]:
        lines.append(f"| {name} | {result} |")
    lines.extend(
        [
            "",
            "## Counts",
            "",
            f"- dream_shards: `{fixtures['dream_shards']}`",
            f"- interpretations: `{fixtures['interpretations']}`",
            f"- revision_threads: `{fixtures['revision_threads']}`",
            f"- ledger_events: `{fixtures['ledger_events']}`",
            "",
            "## State Projection",
            "",
        ]
    )
    for record_id, state in fixtures["projection"]:
        lines.append(f"- `{record_id}`: `{state}`")
    lines.extend(
        [
            "",
            "## Limits",
            "",
            "- DE1 does not judge truth, authenticate sources, parse natural language, normalize relative time, generate Growth Proposals, run recall, or connect to OpenClaw/runtime/CLI/adapters.",
            "- Hashes in this report and implementation are deterministic equivalence keys only, not signatures or anti-tamper guarantees.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_report(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_report(), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the DE1 memory substrate baseline report.")
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)
    write_report(Path(args.output))
    return 0


def _run_fixtures(root: Path) -> dict[str, object]:
    store = open_store(root)
    shard_a = _shard("shard:kunming-20260629", "昆明今天下雨了。", "2026-06-29T08:00:00+08:00", "turn:rain-1")
    shard_b = _shard("shard:kunming-20260630", "昆明今天下雨了。", "2026-06-30T08:00:00+08:00", "turn:rain-2")
    correction = _shard("shard:kunming-correction", "上一条天气信息只适用于当天。", "2026-06-30T09:00:00+08:00", "turn:rain-3")
    store.put_dream_shard(shard_a)
    store.put_dream_shard(shard_b)
    store.put_dream_shard(correction)
    interpretation = InterpretationRecord(
        "interpretation:kunming-city",
        shard_a.shard_id,
        InterpretationKind.classification,
        "昆明 is a city.",
        InterpretationAuthoringMode.llm_proposed,
        ("basis:field-style-opaque-ref",),
        ("context:synthetic",),
        UsageState.tentative,
    )
    store.put_interpretation(interpretation)
    thread = RevisionThread(
        "revision:weather-correction",
        (shard_a.shard_id, correction.shard_id),
        (RevisionEdge(correction.shard_id, shard_a.shard_id, RevisionRelation.supersedes, ("basis:explicit-correction",)),),
        ("context:synthetic",),
    )
    store.put_revision_thread(thread)
    transitions = (
        UsageStateTransition("state:rain-active", shard_a.shard_id, UsageState.tentative, UsageState.active, ("reason:initial-use",), "2026-06-29T09:00:00+08:00"),
        UsageStateTransition("state:rain-retired", shard_a.shard_id, UsageState.active, UsageState.retired, ("revision:weather-correction",), "2026-06-30T09:00:00+08:00"),
        UsageStateTransition("state:rain-active-again", shard_a.shard_id, UsageState.retired, UsageState.active, ("reason:historical-review",), "2026-06-30T10:00:00+08:00"),
    )
    for transition in transitions:
        store.record_usage_transition(transition)
    transition_retry = store.record_usage_transition(transitions[0]).idempotent
    idempotent = store.put_dream_shard(shard_a).idempotent
    conflict = _raises(lambda: store.put_dream_shard(_shard(shard_a.shard_id, "different", "2026-06-29T08:00:00+08:00", "turn:rain-1")))
    transition_conflict = _raises(lambda: store.record_usage_transition(UsageStateTransition(transitions[0].transition_id, shard_a.shard_id, UsageState.active, UsageState.retired, (), "2026-06-29T09:00:00+08:00")))
    missing_subject = _raises(lambda: store.put_interpretation(_interpretation("interpretation:missing", "shard:missing")))
    cycle = _raises(
        lambda: RevisionThread(
            "revision:cycle",
            (shard_a.shard_id, shard_b.shard_id),
            (
                RevisionEdge(shard_a.shard_id, shard_b.shard_id, RevisionRelation.supersedes, ()),
                RevisionEdge(shard_b.shard_id, shard_a.shard_id, RevisionRelation.supersedes, ()),
            ),
            (),
        )
    )
    identity_conflict = _raises(lambda: store.put_interpretation(_interpretation(shard_a.shard_id, shard_a.shard_id)))
    reopened = open_store(root)
    orphan_root = root / "orphan-check"
    orphan_store = open_store(orphan_root)
    orphan_store.put_dream_shard(_shard("shard:base", "base", "2026-06-29T08:00:00+08:00", "turn:base"))
    orphan = _shard("shard:orphan", "orphan", "2026-06-29T08:00:00+08:00", "turn:orphan")
    _write_manual_record(orphan_root, "shards", orphan.shard_id, json.loads(canonical_json(orphan)))
    orphan_rejected = _raises(lambda: MemorySubstrateStore(orphan_root))
    projection = tuple(sorted((record_id, state.value) for record_id, state in reopened.state_projection().items()))
    results = (
        ("F-A same text distinct occurrences", "pass" if reopened.get_dream_shard(shard_a.shard_id).content == reopened.get_dream_shard(shard_b.shard_id).content else "fail"),
        ("F-B interpretation separate from shard", "pass" if reopened.get_interpretation(interpretation.interpretation_id).subject_shard_id == shard_a.shard_id else "fail"),
        ("F-C relative time preserved", "pass" if reopened.get_dream_shard(shard_a.shard_id).temporal_context.source_time_expression == "今天" else "fail"),
        ("F-D explicit retirement transition", "pass" if reopened.get_usage_state(shard_a.shard_id) is UsageState.active else "fail"),
        ("F-E state history round-trip", "pass" if len(reopened.read_ledger()) == 8 else "fail"),
        ("F-F missing interpretation subject rejected", "pass" if missing_subject else "fail"),
        ("F-G supersedes cycle rejected", "pass" if cycle else "fail"),
        ("F-H idempotent retry and payload conflict", "pass" if idempotent and transition_retry and conflict and transition_conflict else "fail"),
        ("F-I reopen validates ledger closure", "pass" if orphan_rejected else "fail"),
        ("F-J opaque field-style refs preserved", "pass" if "basis:field-style-opaque-ref" in reopened.get_interpretation(interpretation.interpretation_id).basis_refs else "fail"),
        ("F-K global record identity enforced", "pass" if identity_conflict else "fail"),
    )
    return {
        "results": results,
        "dream_shards": 3,
        "interpretations": 1,
        "revision_threads": 1,
        "ledger_events": len(reopened.read_ledger()),
        "projection": projection,
    }


def _raises(callback) -> bool:
    try:
        callback()
    except ValueError:
        return True
    return False


def _shard(shard_id: str, content: str, captured_at: str, context_ref: str) -> DreamShard:
    return DreamShard(
        shard_id,
        content,
        OriginDescriptor(OriginKind.user_utterance, context_ref, "conversation:synthetic", "user"),
        TemporalContext(captured_at, "今天", captured_at, "zh-CN"),
        (context_ref,),
        UsageState.tentative,
    )


def _interpretation(interpretation_id: str, subject_shard_id: str) -> InterpretationRecord:
    return InterpretationRecord(interpretation_id, subject_shard_id, InterpretationKind.summary, "missing subject", InterpretationAuthoringMode.llm_proposed, (), (), UsageState.tentative)


def _write_manual_record(root: Path, bucket: str, record_id: str, payload: dict) -> None:
    path = root / bucket / (sha256(record_id.encode("utf-8")).hexdigest() + ".json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, sort_keys=True, separators=(",", ":")), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["build_report", "main", "write_report"]
