"""DG1 pure geometry baseline report generator.

Allowed: explicit, non-production Markdown report generation from finite pure
geometry scans.
Forbidden: production state writes, real memory reads, CLI registration,
OpenClaw, Field, Cortex, Recall, Adapter, network, subprocess, or runtime
integration.
"""

from __future__ import annotations

import argparse
import platform
import sys
from pathlib import Path

from nollm.dream_geometry.geometry.chart import make_hex_cell, relative_phase
from nollm.dream_geometry.geometry.coverage import CoverageDirection, compute_distribution
from nollm.dream_geometry.geometry.hexgrid import disk, nearest_axial
from nollm.dream_geometry.geometry.metrics import percentile, phase_recurrence_score, summarize_distributions
from nollm.dream_geometry.geometry.schedules import DEFAULT_PHASE_SAMPLES, LAYER_PHASE_POLICIES, PARAMETER_MATRIX, LayerPhasePolicy, PhaseSchedule, ScaleRotationSchedule
from nollm.dream_geometry.geometry.types import AxialCoord, GeometryTolerance


LAYERS = tuple(range(33))
GAPS = (1, 2, 4, 8, 16)
SOURCE_RADIUS = 3
TARGET_RADIUS = 4
THRESHOLD = 1e-9
TOLERANCE = GeometryTolerance()


def build_report() -> str:
    rows = []
    lines = [
        "# DG1 Pure Geometry Baseline Report",
        "",
        "Generated by `python3 -m nollm.dream_geometry.validation.dg1_baseline_report`.",
        "",
        "## Execution",
        "",
        f"- Python: `{platform.python_version()}`",
        "- numeric_mode: `float64_tolerance`",
        f"- coordinate_abs_tol: `{TOLERANCE.coordinate_abs_tol}`",
        f"- coordinate_rel_tol: `{TOLERANCE.coordinate_rel_tol}`",
        f"- area_abs_tol: `{TOLERANCE.area_abs_tol}`",
        f"- area_rel_tol: `{TOLERANCE.area_rel_tol}`",
        f"- layers: `{LAYERS[0]}..{LAYERS[-1]}`",
        f"- gaps: `{GAPS}`",
        f"- source sample: axial disk radius `{SOURCE_RADIUS}`",
        f"- phase samples: `{tuple((phase.phase_q, phase.phase_r) for phase in DEFAULT_PHASE_SAMPLES)}`",
        f"- layer phase policies: `{tuple(policy.policy_id for policy in LAYER_PHASE_POLICIES)}`",
        f"- threshold: `{THRESHOLD}`",
        "",
        "## Parameter Matrix",
        "",
        "| ID | beta | delta_theta_degrees | role |",
        "|---|---:|---:|---|",
    ]
    for parameter in PARAMETER_MATRIX:
        lines.append(f"| {parameter.parameter_id} | {parameter.beta:.12g} | {parameter.delta_theta_degrees:.12g} | {parameter.role} |")
    lines.extend(
        [
            "",
            "## Metrics",
            "",
            "| parameter | gap | phase | branching mean | branching p95 | branching max | effective count mean | effective count p95 | max mass | nesting tendency | phase recurrence | overlap entropy | residual mean | residual p95 |",
            "|---|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for parameter in PARAMETER_MATRIX:
        schedule = ScaleRotationSchedule(parameter)
        for gap in GAPS:
            for phase in DEFAULT_PHASE_SAMPLES:
                summary = summarize_distributions(
                    parameter.parameter_id,
                    gap,
                    _phase_label(phase),
                    _distributions_for(schedule, gap, phase),
                    _phase_score_for(schedule, gap, phase, LayerPhasePolicy.constant_local()),
                )
                rows.append(summary)
                lines.append(
                    "| "
                    + " | ".join(
                        [
                            summary.parameter_id,
                            str(summary.gap),
                            summary.phase_label,
                            f"{_mean_int(summary.branching_factors):.4f}",
                            f"{percentile(summary.branching_factors, 95):.4f}",
                            str(max(summary.branching_factors) if summary.branching_factors else 0),
                            f"{_mean(summary.effective_parent_counts):.4f}",
                            f"{percentile(summary.effective_parent_counts, 95):.4f}",
                            f"{max(summary.max_coverage_masses) if summary.max_coverage_masses else 0.0:.6f}",
                            f"{summary.multi_layer_nesting_tendency:.6f}",
                            f"{summary.phase_recurrence_score:.6f}",
                            f"{summary.repeat_overlap_entropy:.6f}",
                            f"{_mean(summary.residual_masses):.6f}",
                            f"{percentile(summary.residual_masses, 95):.6f}",
                        ]
                    )
                    + " |"
                )
    baseline_rows = [row for row in rows if row.parameter_id == "B" and row.gap in (8, 16)]
    lines.extend(
        [
            "",
            "## Current Baseline B Focus",
            "",
            "The current engineering baseline is parameter `B`: beta `2^(1/4)`, delta theta `22.5` degrees.",
            "",
            "| gap | phase | rotation recurrence mod 60 | side ratio | branching p95 | max mass | nesting tendency |",
            "|---:|---|---|---:|---:|---:|---:|",
        ]
    )
    for row in baseline_rows:
        rotation_recurrence = "yes" if (22.5 * row.gap) % 60.0 == 0.0 else "no"
        side_ratio = (2.0 ** 0.25) ** (-row.gap)
        lines.append(
            f"| {row.gap} | {row.phase_label} | {rotation_recurrence} | {side_ratio:.8f} | "
            f"{percentile(row.branching_factors, 95):.4f} | {max(row.max_coverage_masses):.6f} | {row.multi_layer_nesting_tendency:.6f} |"
        )
    lines.extend(
        [
            "",
            "## Relative Phase Recurrence Diagnostics",
            "",
            "Relative phase recurrence is computed from `phase(source_layer <- target_layer)` over fixed-gap pairs `layer -> layer + gap`.",
            "",
            "| parameter | phase policy | base phase | gap | sample count | phase recurrence score | rotation recurrence mod 60 |",
            "|---|---|---|---:|---:|---:|---|",
        ]
    )
    for parameter in PARAMETER_MATRIX:
        schedule = ScaleRotationSchedule(parameter)
        for policy in LAYER_PHASE_POLICIES:
            for phase in DEFAULT_PHASE_SAMPLES:
                for gap in GAPS:
                    rotation_recurrence = "yes" if (parameter.delta_theta_degrees * gap) % 60.0 == 0.0 else "no"
                    sample_count = 33 - gap
                    lines.append(
                        f"| {parameter.parameter_id} | {policy.policy_id} | {_phase_label(phase)} | {gap} | {sample_count} | "
                        f"{_phase_score_for(schedule, gap, phase, policy):.6f} | {rotation_recurrence} |"
                    )
    lines.extend(
        [
            "",
            "## Observations",
            "",
            "- All A-E parameter sets can be evaluated on layers 0..32 with finite source and target windows.",
            "- Baseline B has exact rotation recurrence modulo 60 degrees at gap 8 and gap 16 in this schedule.",
            "- Baseline B side ratio at gap 8 is 0.25 and at gap 16 is 0.0625.",
            "- Branching, entropy, residual, and nesting values are finite-window signals, not global proofs.",
            "",
            "## Conclusion Limits",
            "",
            "- DG1 does not select a final beta/theta/phase policy.",
            "- DG1 uses float64 tolerance, not exact algebraic-number computation.",
            "- Phase samples are synthetic local-chart offsets and do not represent final global translation policy.",
            "- rotation recurrence reports angle modulo 60 degrees; relative phase recurrence reports phase(layer <- layer + gap) over fixed-gap layer pairs; coverage recurrence is represented by quantized overlap entropy.",
            "- `constant_local` and `layer_drift_control` are finite-window diagnostic phase policies only, not final global translation policies.",
            "- This report does not prove runtime recall, OpenClaw behavior, Field Dynamics, Query Probe behavior, or memory quality.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_report(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_report(), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the DG1 pure geometry baseline report.")
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)
    write_report(Path(args.output))
    return 0


def _distributions_for(schedule: ScaleRotationSchedule, gap: int, phase: PhaseSchedule):
    source_chart = schedule.chart_for_layer(gap, phase)
    target_chart = schedule.chart_for_layer(0, phase)
    distributions = []
    for axial in disk(AxialCoord(0, 0), SOURCE_RADIUS):
        source_cell = make_hex_cell(source_chart, axial)
        target_center = nearest_axial(target_chart, source_cell.center)
        targets = tuple(make_hex_cell(target_chart, target) for target in disk(target_center, TARGET_RADIUS))
        distributions.append(compute_distribution(source_cell, targets, CoverageDirection.fine_to_coarse, THRESHOLD, TOLERANCE))
    return tuple(distributions)


def _phase_score_for(
    schedule: ScaleRotationSchedule,
    gap: int,
    phase: PhaseSchedule,
    policy: LayerPhasePolicy = LayerPhasePolicy.constant_local(),
) -> float:
    phases = tuple(
        relative_phase(
            schedule.chart_for_layer(base_layer, policy.phase_for_layer(phase, base_layer)),
            schedule.chart_for_layer(base_layer + gap, policy.phase_for_layer(phase, base_layer + gap)),
        )
        for base_layer in range(0, 33 - gap)
    )
    return phase_recurrence_score(phases)


def _phase_label(phase: PhaseSchedule) -> str:
    return f"({phase.phase_q:.6g},{phase.phase_r:.6g})"


def _mean(values) -> float:
    return sum(values) / len(values) if values else 0.0


def _mean_int(values: tuple[int, ...]) -> float:
    return sum(values) / len(values) if values else 0.0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["build_report", "main", "write_report"]
