"""DG2 deterministic Field Dynamics baseline report generator."""

from __future__ import annotations

import argparse
import platform
from pathlib import Path

from nollm.dream_geometry.field import build_local_covers, calculate_gravity_snapshot, compact_traces, expand_compaction, propagate_trace, seed_to_trace
from nollm.dream_geometry.field.types import GrowthTrace, TraceSeed
from nollm.dream_geometry.geometry.chart import make_hex_cell
from nollm.dream_geometry.geometry.coverage import CoverageDirection, compute_distribution
from nollm.dream_geometry.geometry.hexgrid import disk
from nollm.dream_geometry.geometry.transform import SimilarityTransform, TransformWitness, validate_transform
from nollm.dream_geometry.geometry.types import AxialCoord, LocalChart, Vec2
from nollm.dream_geometry.protocol.contracts import GrowthBasis, TraceState


def build_report() -> str:
    fixtures = _fixtures()
    propagation = fixtures["propagation"]
    covers = fixtures["covers"]
    gravity = fixtures["gravity"]
    compacted = fixtures["compacted"]
    expanded = fixtures["expanded"]
    lines = [
        "# DG2 Field Dynamics Baseline Report",
        "",
        "Generated by `python3 -m nollm.dream_geometry.validation.dg2_field_report`.",
        "",
        "## Execution",
        "",
        f"- Python: `{platform.python_version()}`",
        "- third_party_dependencies: `none`",
        "- fixture_data: `synthetic_only`",
        "",
        "## Fixtures",
        "",
        "- F1: one accepted trace propagated through a DG1 K_up distribution with explicit residual.",
        "- F2: two accepted axes and two independent support keys in one cell form a stable cover.",
        "- F3: high-mass single-axis generic support remains candidate and produces no gravity.",
        "- F4: provisional / ambiguous / conflicted traces remain candidate.",
        "- F5: cross-chart propagation requires a supplied verified chart link.",
        "- F6: compatible traces compact and expand losslessly.",
        "",
        "## Propagation",
        "",
        "| case | parent mass | derived mass | residual mass | accounting error | residual reasons |",
        "|---|---:|---:|---:|---:|---|",
        f"| F1 | {propagation.parent_mass:.6f} | {propagation.derived_mass:.6f} | {propagation.residual.mass:.6f} | {propagation.accounting_error:.6g} | {','.join(propagation.residual.reasons)} |",
        "",
        "## Covers",
        "",
        "| cover_id | state | mass | support_keys | axes | reasons |",
        "|---|---|---:|---|---|---|",
    ]
    for cover in covers:
        lines.append(
            f"| {cover.cover_id} | {cover.state.value} | {cover.mass:.6f} | {','.join(cover.support_keys)} | "
            f"{','.join(cover.axes_present)} | {','.join(cover.eligibility_reasons)} |"
        )
    lines.extend(
        [
            "",
            "## Gravity",
            "",
            "| cover_id | potential | support_term | penalties | policy |",
            "|---|---:|---:|---|---|",
        ]
    )
    for contribution in gravity.contributions:
        penalties = ",".join(f"{name}:{value:.6f}" for name, value in contribution.penalty_terms)
        lines.append(f"| {contribution.cover_id} | {contribution.potential:.6f} | {contribution.support_term:.6f} | {penalties} | {contribution.policy_id} |")
    lines.extend(
        [
            "",
            "## Compaction",
            "",
            f"- compaction_count: `{len(compacted)}`",
            f"- expanded_trace_ids: `{tuple(trace.trace_id for trace in expanded)}`",
            "",
            "## Limits",
            "",
            "- DG2 does not implement Cortex, Query Probe, Recall Resolver, runtime, OpenClaw, adapter, CLI, memory, Evidence persistence, ledger writes, or final parameter selection.",
            "- Gravity weights are deterministic baseline policy values, not production-calibrated parameters.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_report(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_report(), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the DG2 field dynamics baseline report.")
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)
    write_report(Path(args.output))
    return 0


def _fixtures() -> dict[str, object]:
    chart = LocalChart("dg2", 0, 1.0, 0.0, Vec2(0, 0))
    cell = make_hex_cell(chart, AxialCoord(0, 0))
    parent = seed_to_trace(_seed("seed", cell, "location", "s1"))
    distribution = compute_distribution(cell, (cell,), CoverageDirection.fine_to_coarse, threshold=1.1)
    propagation = propagate_trace(parent, distribution)
    traces = (
        _trace("t1", cell, "location", "s1"),
        _trace("t2", cell, "phenomenon", "s2"),
        _trace("t3", make_hex_cell(chart, AxialCoord(2, 0)), "generic", "s3", mass=10.0, genericity=0.9),
        _trace("t4", make_hex_cell(chart, AxialCoord(3, 0)), "location", "s4", ambiguity=0.9, conflict=0.9),
    )
    covers = build_local_covers(traces)
    gravity = calculate_gravity_snapshot(covers)
    duplicate = _trace("t5", cell, "location", "s1")
    duplicate_peer = GrowthTrace(**{**duplicate.__dict__, "trace_id": "t6"})
    compacted = compact_traces((duplicate, duplicate_peer))
    expanded = expand_compaction(compacted[0], {"t5": duplicate, "t6": duplicate_peer}) if compacted else ()
    return {"propagation": propagation, "covers": covers, "gravity": gravity, "compacted": compacted, "expanded": expanded}


def _seed(trace_id: str, cell, axis: str, support_key: str) -> TraceSeed:
    return TraceSeed(trace_id, f"shard-{trace_id}", "proposal", cell, axis, GrowthBasis.explicit_in_shard, ("basis",), 1.0, support_key, 0.1, 0.1, 0.0, 2, TraceState.accepted)


def _trace(trace_id: str, cell, axis: str, support_key: str, mass: float = 0.3, genericity: float = 0.1, ambiguity: float = 0.1, conflict: float = 0.0) -> GrowthTrace:
    return GrowthTrace(trace_id, f"shard-{support_key}", "proposal", "parent", cell, axis, GrowthBasis.explicit_in_shard, ("basis",), mass, support_key, genericity, ambiguity, conflict, 2, TraceState.accepted, "synthetic", ("geometry",))


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["build_report", "main", "write_report"]
