"""DG2 deterministic Field Dynamics baseline report generator."""

from __future__ import annotations

import argparse
import platform
from dataclasses import replace
from pathlib import Path

from nollm.dream_geometry.field import CoverPolicy, build_local_covers, calculate_gravity_snapshot, compact_traces, crystallize_cover, evaluate_cover_eligibility, expand_compaction, propagate_trace, seed_to_trace
from nollm.dream_geometry.field.types import CrystallizationDecision, GrowthTrace, TraceCompaction, TraceSeed
from nollm.dream_geometry.geometry.chart import make_hex_cell
from nollm.dream_geometry.geometry.coverage import CoverageDirection, compute_distribution
from nollm.dream_geometry.geometry.hexgrid import disk
from nollm.dream_geometry.geometry.transform import SimilarityTransform, TransformWitness, validate_transform
from nollm.dream_geometry.geometry.types import AxialCoord, LocalChart, Vec2
from nollm.dream_geometry.protocol.contracts import CoverState, GrowthBasis, TraceState


def build_report() -> str:
    fixtures = _fixtures()
    propagation = fixtures["propagation"]
    covers = fixtures["covers"]
    gravity = fixtures["gravity"]
    compacted = fixtures["compacted"]
    expanded = fixtures["expanded"]
    integrity = fixtures["integrity"]
    lines = [
        "# DG2 Field Dynamics Baseline Report",
        "",
        "Generated by `python3 -m nollm.dream_geometry.validation.dg2_field_report`.",
        "",
        "## Execution",
        "",
        f"- Python: `{platform.python_version()}`",
        "- third_party_dependencies: `none`",
        "- fixture_data: `synthetic_only`",
        "",
        "## Fixtures",
        "",
        "- F1: one accepted trace propagated through a DG1 K_up distribution with explicit residual.",
        "- F2: two accepted axes and two independent support keys in one cell form a stable cover.",
        "- F3: high-mass single-axis generic support remains candidate and produces no gravity.",
        "- F4: provisional / ambiguous / conflicted traces remain candidate.",
        "- F5: cross-chart propagation requires a supplied verified chart link.",
        "- F6: compatible traces compact and expand losslessly.",
        "",
        "## Propagation",
        "",
        "| case | parent mass | derived mass | residual mass | accounting error | residual reasons |",
        "|---|---:|---:|---:|---:|---|",
        f"| F1 | {propagation.parent_mass:.6f} | {propagation.derived_mass:.6f} | {propagation.residual.mass:.6f} | {propagation.accounting_error:.6g} | {','.join(propagation.residual.reasons)} |",
        "",
        "## Covers",
        "",
        "| cover_id | state | mass | support_keys | axes | reasons |",
        "|---|---|---:|---|---|---|",
    ]
    for cover in covers:
        lines.append(
            f"| {cover.cover_id} | {cover.state.value} | {cover.mass:.6f} | {','.join(cover.support_keys)} | "
            f"{','.join(cover.axes_present)} | {','.join(cover.eligibility_reasons)} |"
        )
    lines.extend(
        [
            "",
            "## Gravity",
            "",
            "| cover_id | potential | support_term | penalties | policy |",
            "|---|---:|---:|---|---|",
        ]
    )
    for contribution in gravity.contributions:
        penalties = ",".join(f"{name}:{value:.6f}" for name, value in contribution.penalty_terms)
        lines.append(f"| {contribution.cover_id} | {contribution.potential:.6f} | {contribution.support_term:.6f} | {penalties} | {contribution.policy_id} |")
    lines.extend(
        [
            "",
            "## Compaction",
            "",
            f"- compaction_count: `{len(compacted)}`",
            f"- expanded_trace_ids: `{tuple(trace.trace_id for trace in expanded)}`",
            "",
            "## Integrity Checks",
            "",
            "| check | result |",
            "|---|---|",
        ]
    )
    for name, result in integrity:
        lines.append(f"| {name} | {result} |")
    lines.extend(
        [
            "",
            "## Limits",
            "",
            "- DG2 does not implement Cortex, Query Probe, Recall Resolver, runtime, OpenClaw, adapter, CLI, memory, Evidence persistence, ledger writes, or final parameter selection.",
            "- Gravity weights are deterministic baseline policy values, not production-calibrated parameters.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_report(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_report(), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the DG2 field dynamics baseline report.")
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)
    write_report(Path(args.output))
    return 0


def _fixtures() -> dict[str, object]:
    chart = LocalChart("dg2", 0, 1.0, 0.0, Vec2(0, 0))
    cell = make_hex_cell(chart, AxialCoord(0, 0))
    parent = seed_to_trace(_seed("seed", cell, "location", "s1"))
    distribution = compute_distribution(cell, (cell,), CoverageDirection.fine_to_coarse, threshold=1.1)
    propagation = propagate_trace(parent, distribution)
    traces = (
        _trace("t1", cell, "location", "s1"),
        _trace("t2", cell, "phenomenon", "s2"),
        _trace("t3", make_hex_cell(chart, AxialCoord(2, 0)), "generic", "s3", mass=10.0, genericity=0.9),
        _trace("t4", make_hex_cell(chart, AxialCoord(3, 0)), "location", "s4", ambiguity=0.9, conflict=0.9),
    )
    covers = build_local_covers(traces)
    gravity = calculate_gravity_snapshot(covers)
    duplicate = _trace("t5", cell, "location", "s1")
    duplicate_peer = GrowthTrace(**{**duplicate.__dict__, "trace_id": "t6"})
    compacted = compact_traces((duplicate, duplicate_peer))
    expanded = expand_compaction(compacted[0], {"t5": duplicate, "t6": duplicate_peer}) if compacted else ()
    integrity = _integrity_checks(cell)
    return {"propagation": propagation, "covers": covers, "gravity": gravity, "compacted": compacted, "expanded": expanded, "integrity": integrity}


def _integrity_checks(cell) -> tuple[tuple[str, str], ...]:
    tiny_parent = replace(seed_to_trace(_seed("tiny", cell, "location", "tiny-support")), mass=1e-13)
    tiny_distribution = compute_distribution(cell, (cell,), CoverageDirection.fine_to_coarse)
    tiny = propagate_trace(tiny_parent, tiny_distribution)
    tiny_result = "pass" if len(tiny.derived_traces) == 1 and tiny.derived_traces[0].mass == 1e-13 and tiny.residual.mass == 0.0 else "fail"

    duplicate_trace = _trace("dup", cell, "location", "s1")
    duplicate_trace_result = _raises_value_error(lambda: build_local_covers((duplicate_trace, duplicate_trace)), "duplicate trace_id")

    stable_cover = build_local_covers((_trace("g1", cell, "location", "s1"), _trace("g2", cell, "phenomenon", "s2")))[0]
    duplicate_cover_result = _raises_value_error(lambda: calculate_gravity_snapshot((stable_cover, stable_cover)), "duplicate cover_id")

    policy_a = build_local_covers((_trace("p1", cell, "location", "s1"), _trace("p2", cell, "phenomenon", "s2")), CoverPolicy(policy_id="a"))[0]
    policy_b = build_local_covers((_trace("p1", cell, "location", "s1"), _trace("p2", cell, "phenomenon", "s2")), CoverPolicy(policy_id="b"))[0]
    policy_result = "pass" if policy_a.policy_id == "a" and policy_b.policy_id == "b" and policy_a.policy_fingerprint != policy_b.policy_fingerprint and policy_a.cover_id != policy_b.cover_id else "fail"

    provisional = build_local_covers((_trace("c1", cell, "location", "s1"), _trace("c2", cell, "phenomenon", "s2", state=TraceState.proposed)))[0]
    forged_stable_result = _raises_value_error(lambda: replace(provisional, state=CoverState.stable), "provisional")
    crystallize_recheck_result = _raises_value_error(lambda: crystallize_cover(_forge_cover(provisional, state=CoverState.stable), CrystallizationDecision("d", provisional.cover_id, True, "operator", ("basis",))), "provisional")

    strict = CoverPolicy(policy_id="same", version="1", min_total_mass=1.0)
    loose = CoverPolicy(policy_id="same", version="1", min_total_mass=0.1)
    strict_cover = build_local_covers((_trace("p3", cell, "location", "s1"), _trace("p4", cell, "phenomenon", "s2")), strict)[0]
    fingerprint_result = "pass" if strict.policy_fingerprint != loose.policy_fingerprint else "fail"
    evaluator_result = _raises_value_error(lambda: evaluate_cover_eligibility(strict_cover, loose), "policy identity mismatch")

    manifest_result = _raises_value_error(lambda: TraceCompaction("bad", ("t1", "t2"), "k", 0.6, ("t1",)), "manifest")

    return (
        ("tiny positive mass retained", tiny_result),
        ("duplicate trace rejected", duplicate_trace_result),
        ("duplicate cover rejected", duplicate_cover_result),
        ("policy identity visible", policy_result),
        ("forged stable cover rejected", forged_stable_result),
        ("crystallization structural recheck", crystallize_recheck_result),
        ("policy fingerprint differs by semantics", fingerprint_result),
        ("policy fingerprint mismatch rejected", evaluator_result),
        ("compaction manifest matches members", manifest_result),
    )


def _raises_value_error(callback, expected: str) -> str:
    try:
        callback()
    except ValueError as exc:
        return "pass" if expected in str(exc) else "fail"
    return "fail"


def _forge_cover(cover, **changes):
    values = {field: getattr(cover, field) for field in cover.__dataclass_fields__}
    values.update(changes)
    forged = object.__new__(type(cover))
    for field, value in values.items():
        object.__setattr__(forged, field, value)
    return forged


def _seed(trace_id: str, cell, axis: str, support_key: str) -> TraceSeed:
    return TraceSeed(trace_id, f"shard-{trace_id}", "proposal", cell, axis, GrowthBasis.explicit_in_shard, ("basis",), 1.0, support_key, 0.1, 0.1, 0.0, 2, TraceState.accepted)


def _trace(
    trace_id: str,
    cell,
    axis: str,
    support_key: str,
    mass: float = 0.3,
    genericity: float = 0.1,
    ambiguity: float = 0.1,
    conflict: float = 0.0,
    state: TraceState = TraceState.accepted,
) -> GrowthTrace:
    return GrowthTrace(trace_id, f"shard-{support_key}", "proposal", "parent", cell, axis, GrowthBasis.explicit_in_shard, ("basis",), mass, support_key, genericity, ambiguity, conflict, 2, state, "synthetic", ("geometry",))


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["build_report", "main", "write_report"]
