"""DI1 Integration Shell deterministic baseline report generator."""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import tempfile
from pathlib import Path

from nollm.dream_geometry.adapters import CapabilitiesInvocation, IntegrationShell
from nollm.dream_geometry.validation.di1_integration_fixture import build_deferred_context, build_di1_context


def canonical_fingerprint(mapping: dict) -> str:
    rendered = json.dumps(mapping, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return "sha256:" + hashlib.sha256(rendered.encode("utf-8")).hexdigest()


def build_report() -> str:
    shell = IntegrationShell()
    with tempfile.TemporaryDirectory(prefix="di1-report-") as directory:
        root = Path(directory)
        store, _, _, invocation, context = build_di1_context(root)
        resolved = shell.handle(invocation, context).to_mapping()
        rerun = shell.handle(invocation, context).to_mapping()
        deferred = shell.handle(build_deferred_context(root / "deferred")[3], build_deferred_context(root / "deferred2")[4]).to_mapping()
        capabilities = shell.handle(CapabilitiesInvocation("req-di1-capabilities-001", "capabilities")).to_mapping()
        ledger_before = len(store.read_ledger())
        shell.handle(invocation, context)
        ledger_after = len(store.read_ledger())
    allowed_result_fields = sorted(resolved["result"].keys())
    lines = [
        "# DI1 Integration Shell Baseline Report",
        "",
        "Generated by `python -m nollm.dream_geometry.validation.di1_integration_shell_report`.",
        "",
        "## Execution",
        "",
        f"- Python: `{platform.python_version()}`",
        "- baseline_commit: `recorded in delivery receipt`",
        "- contract: `di1.integration_shell.v1`",
        "- fixture_data: `synthetic_only`",
        "- third_party_dependencies: `none`",
        "",
        "## Public Operations",
        "",
        "- `capabilities`",
        "- `recall`",
        "",
        "## Public Response Allowlist",
        "",
        f"- result_fields: `{tuple(allowed_result_fields)}`",
        "- evidence_fields: `evidence_kind, shard_id, content, usage_state, tier, matched_axis_ids, selection_basis, origin, temporal_context, interpretation_context, revision_context`",
        "- hidden_internal_categories: `internal tie-break data, structure metrics, traversal identifiers, cell or chart references, cover or trace identifiers, filesystem locations`",
        "",
        "## Fixture Results",
        "",
        "| fixture | result |",
        "|---|---|",
        f"| capabilities without context | {'pass' if capabilities['ok'] and capabilities['result']['capabilities'] == ['capabilities', 'recall'] else 'fail'} |",
        f"| resolved recall envelope | {'pass' if resolved['ok'] and resolved['result']['status'] == 'resolved' else 'fail'} |",
        f"| primary evidence materialized | {'pass' if resolved['result']['primary_evidence'] and resolved['result']['primary_evidence'][0]['content'] == 'Kunming had rain on 2026-06-29.' else 'fail'} |",
        f"| deferred relative-time status preserved | {'pass' if deferred['ok'] and deferred['result']['status'] == 'deferred' else 'fail'} |",
        f"| deterministic mapping fingerprint stable | {'pass' if canonical_fingerprint(resolved) == canonical_fingerprint(rerun) else 'fail'} |",
        f"| no ledger writes | {'pass' if ledger_before == ledger_after else 'fail'} |",
        "",
        "## Deterministic Fingerprints",
        "",
        f"- resolved: `{canonical_fingerprint(resolved)}`",
        f"- capabilities: `{canonical_fingerprint(capabilities)}`",
        "",
        "## Explicit Non-Goals",
        "",
        "- No JSON input codec, HTTP, CLI, OpenClaw, runtime hook, network, database, cache, session, or write path.",
        "- No Query compilation, RecallUniverse construction, global window admission, semantic search, embedding, or memory scanning.",
        "- No public exposure of internal Field, Geometry, traversal, or tie-break internals.",
    ]
    return "\n".join(lines) + "\n"


def default_output_path() -> Path:
    return Path(__file__).resolve().parents[5] / "docs" / "validation" / "DI1_INTEGRATION_SHELL_BASELINE_REPORT.md"


def write_report(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_report(), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the DI1 Integration Shell baseline report.")
    parser.add_argument("--output", default=str(default_output_path()))
    args = parser.parse_args(argv)
    write_report(Path(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["build_report", "canonical_fingerprint", "default_output_path", "main", "write_report"]
