"""DX1 synthetic end-to-end memory cycle baseline report generator."""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import sys
import tempfile
from pathlib import Path

REFERENCE_PYTHON = Path(__file__).resolve().parents[3]
if str(REFERENCE_PYTHON) not in sys.path:
    sys.path.insert(0, str(REFERENCE_PYTHON))

from nollm.dream_geometry.adapters import IntegrationShell
from nollm.dream_geometry.recall import resolve_recall
from nollm.dream_geometry.recall.universe import validate_recall_universe
from nollm.dream_geometry.validation.dx1_synthetic_cycle_fixture import (
    TARGET_SHARD_ID,
    build_dx1_cycle,
    build_dx1_deferred_cycle,
    build_dx1_retired_cycle,
    canonical_mapping,
    tree_manifest,
)


def canonical_fingerprint(mapping: dict) -> str:
    rendered = json.dumps(mapping, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return "sha256:" + hashlib.sha256(rendered.encode("utf-8")).hexdigest()


def build_report() -> str:
    shell = IntegrationShell()
    with tempfile.TemporaryDirectory(prefix="dx1-report-") as directory:
        root = Path(directory)
        fixture = build_dx1_cycle(root / "baseline")
        validate_recall_universe(fixture.recall_universe, fixture.evidence_store)
        digest = resolve_recall(
            fixture.compiled_query_probe,
            fixture.recall_universe,
            fixture.evidence_store,
            runtime_time=fixture.runtime_time_resolution,
            policy=fixture.policy,
        )
        resolved = shell.handle(fixture.invocation, fixture.integration_context).to_mapping()
        rerun = shell.handle(fixture.invocation, fixture.integration_context).to_mapping()
        mismatch = shell.handle(fixture.mismatch_invocation, fixture.integration_context).to_mapping()
        deferred = shell.handle(build_dx1_deferred_cycle(root / "deferred").invocation, build_dx1_deferred_cycle(root / "deferred2").integration_context).to_mapping()
        retired_fixture = build_dx1_retired_cycle(root / "retired")
        retired = shell.handle(retired_fixture.invocation, retired_fixture.integration_context).to_mapping()
        permuted = build_dx1_cycle(root / "permuted", permuted=True)
        permuted_response = shell.handle(permuted.invocation, permuted.integration_context).to_mapping()
        after_manifests = {"evidence": tree_manifest(fixture.root / "evidence"), "cortex": tree_manifest(fixture.root / "cortex")}

    primary = resolved["result"]["primary_evidence"]
    contextual_retired = retired["result"]["contextual_evidence"]
    lines = [
        "# DX1 Synthetic Memory Cycle Baseline Report",
        "",
        "Generated by `python -m nollm.dream_geometry.validation.dx1_synthetic_cycle_report`.",
        "",
        "## Execution",
        "",
        f"- Python: `{platform.python_version()}`",
        "- baseline_commit: `recorded in delivery receipt`",
        "- contract: `dx1.synthetic_memory_cycle.v1`",
        "- fixture_data: `synthetic_only`",
        "- third_party_dependencies: `none`",
        "",
        "## Real Public API Chain",
        "",
        "- DE1: `open_store`, `put_dream_shard`, `put_interpretation`, `put_revision_thread`, `record_usage_transition`, public readers.",
        "- DC1: `CortexStore.compile_growth`, `compile_query`, stored current proposal readback.",
        "- DG1: `make_hex_cell`, `compute_distribution`.",
        "- DG2: `TraceSeed`, `seed_to_trace`, `propagate_trace`, `build_local_covers`, `calculate_gravity_snapshot`.",
        "- DR1: `validate_recall_universe`, `resolve_recall`.",
        "- DI1: `IntegrationShell.handle` public recall envelope.",
        "",
        "## Scenario Results",
        "",
        "| scenario | result |",
        "|---|---|",
        f"| S01 full synthetic cycle resolves one primary target | {'pass' if resolved['ok'] and resolved['result']['status'] == 'resolved' and len(primary) == 1 and primary[0]['shard_id'] == TARGET_SHARD_ID else 'fail'} |",
        f"| S02 missing runtime relative-time resolution defers without evidence | {'pass' if deferred['ok'] and deferred['result']['status'] == 'deferred' and not deferred['result']['primary_evidence'] else 'fail'} |",
        f"| S03 exact mismatch does not recall target | {'pass' if mismatch['ok'] and mismatch['result']['status'] != 'resolved' and not mismatch['result']['primary_evidence'] else 'fail'} |",
        f"| S04 retired target is context only | {'pass' if retired['ok'] and not retired['result']['primary_evidence'] and any(item['shard_id'] == TARGET_SHARD_ID for item in contextual_retired) else 'fail'} |",
        f"| S05 public envelope hides internal geometry and private provenance | `covered by test_dx1_synthetic_memory_cycle_boundaries.py` |",
        f"| S06 same input rerun has stable public mapping and no persistence | {'pass' if canonical_mapping(resolved) == canonical_mapping(rerun) and fixture.before_recall_manifests == after_manifests else 'fail'} |",
        f"| S07 input permutation keeps public mapping | {'pass' if canonical_mapping(resolved) == canonical_mapping(permuted_response) else 'fail'} |",
        "",
        "## Deterministic Fingerprints",
        "",
        f"- resolved_public_envelope: `{canonical_fingerprint(resolved)}`",
        f"- mismatch_public_envelope: `{canonical_fingerprint(mismatch)}`",
        f"- deferred_public_envelope: `{canonical_fingerprint(deferred)}`",
        f"- digest_status: `{digest.status.value}`",
        f"- traversal_records: `{len(digest.traversal_records)}`",
        "",
        "## Boundary Statement",
        "",
        "- DX1 constructs only synthetic validation fixtures and reports.",
        "- DX1 does not modify sealed Geometry, Field, Evidence, Cortex, Recall, or Adapter implementation modules.",
        "- DX1 does not add NLP, embeddings, semantic search, anchor retrieval, LLM calls, OpenClaw, runtime, CLI, network, database, cache, session, real memory, or global window admission.",
        "- DX1 does not expose Gravity, scores, mass, cells, charts, covers, traces, kernels, or route paths through the public DI1 envelope.",
    ]
    return "\n".join(lines) + "\n"


def default_output_path() -> Path:
    return Path(__file__).resolve().parents[5] / "docs" / "validation" / "DX1_SYNTHETIC_MEMORY_CYCLE_BASELINE_REPORT.md"


def write_report(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_report(), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the DX1 synthetic memory cycle baseline report.")
    parser.add_argument("--output", default=str(default_output_path()))
    args = parser.parse_args(argv)
    write_report(Path(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["build_report", "canonical_fingerprint", "default_output_path", "main", "write_report"]
