"""DA1 deterministic admission error codes."""

from __future__ import annotations

from dataclasses import dataclass


DA1_INVALID_ROOT_CONFIGURATION = "DA1_INVALID_ROOT_CONFIGURATION"
DA1_ADMISSION_ID_PAYLOAD_CONFLICT = "DA1_ADMISSION_ID_PAYLOAD_CONFLICT"
DA1_PROPOSAL_ALREADY_ADMITTED = "DA1_PROPOSAL_ALREADY_ADMITTED"
DA1_SUBJECT_SHARD_MISMATCH = "DA1_SUBJECT_SHARD_MISMATCH"
DA1_MULTI_STEP_RAY_DEFERRED = "DA1_MULTI_STEP_RAY_DEFERRED"
DA1_PLACEMENT_AXIS_MISMATCH = "DA1_PLACEMENT_AXIS_MISMATCH"
DA1_PLACEMENT_STEP_MISMATCH = "DA1_PLACEMENT_STEP_MISMATCH"
DA1_DUPLICATE_PLACEMENT = "DA1_DUPLICATE_PLACEMENT"
DA1_INVALID_FINE_TO_COARSE_PARTITION = "DA1_INVALID_FINE_TO_COARSE_PARTITION"
DA1_UNVERIFIED_CROSS_CHART_LINK = "DA1_UNVERIFIED_CROSS_CHART_LINK"
DA1_FIELD_PROFILE_OVERRIDE_FORBIDDEN = "DA1_FIELD_PROFILE_OVERRIDE_FORBIDDEN"
DA1_LEGACY_PROPOSAL_NOT_ADMISSIBLE = "DA1_LEGACY_PROPOSAL_NOT_ADMISSIBLE"
DA1_PREFLIGHT_PROJECTION_FAILURE = "DA1_PREFLIGHT_PROJECTION_FAILURE"
DA1_CORTEX_PREVIEW_COMMIT_MISMATCH = "DA1_CORTEX_PREVIEW_COMMIT_MISMATCH"
DA1_CORTEX_COMMIT_FAILED = "DA1_CORTEX_COMMIT_FAILED"
DA1_ADMISSION_RECORD_COMMIT_FAILED = "DA1_ADMISSION_RECORD_COMMIT_FAILED"
DA1_ADMISSION_RECORD_REFERENCE_MISSING = "DA1_ADMISSION_RECORD_REFERENCE_MISSING"
DA1_REPLAY_PROJECTION_MISMATCH = "DA1_REPLAY_PROJECTION_MISMATCH"
DA1_INTERNAL_FIELD_DETAIL_EXPOSED = "DA1_INTERNAL_FIELD_DETAIL_EXPOSED"
DA1_INVALID_RECORDED_AT = "DA1_INVALID_RECORDED_AT"


@dataclass
class DA1Rejection(ValueError):
    """A narrow DA1 rejection with stable machine-readable reason codes."""

    reason_codes: tuple[str, ...]
    detail: str
    stage: str = "preflight"

    def __str__(self) -> str:
        return f"{self.stage}:{','.join(self.reason_codes)}: {self.detail}"


def reject(code: str, detail: str, *, stage: str = "preflight") -> None:
    raise DA1Rejection((code,), detail, stage)


__all__ = [name for name in globals() if name.startswith("DA1_")] + ["DA1Rejection", "reject"]
