"""Stable DC1 rejection codes and structured exceptions."""

from __future__ import annotations

from dataclasses import dataclass


DC1_UNKNOWN_FIELD = "DC1_UNKNOWN_FIELD"
DC1_MISSING_REQUIRED_FIELD = "DC1_MISSING_REQUIRED_FIELD"
DC1_INVALID_ID = "DC1_INVALID_ID"
DC1_INVALID_ENUM = "DC1_INVALID_ENUM"
DC1_INVALID_TIME_FORMAT = "DC1_INVALID_TIME_FORMAT"
DC1_INVALID_AXIS = "DC1_INVALID_AXIS"
DC1_DUPLICATE_AXIS = "DC1_DUPLICATE_AXIS"
DC1_DUPLICATE_STEP_ID = "DC1_DUPLICATE_STEP_ID"
DC1_DUPLICATE_RAY_EXPRESSION = "DC1_DUPLICATE_RAY_EXPRESSION"
DC1_BUDGET_EXCEEDED = "DC1_BUDGET_EXCEEDED"
DC1_EMPTY_FORBIDDEN_INFERENCE = "DC1_EMPTY_FORBIDDEN_INFERENCE"
DC1_EMPTY_DO_NOT_INFER = "DC1_EMPTY_DO_NOT_INFER"
DC1_GROWTH_RELATIVE_TIME_FORBIDDEN = "DC1_GROWTH_RELATIVE_TIME_FORBIDDEN"
DC1_QUERY_MEMORY_BASIS_FORBIDDEN = "DC1_QUERY_MEMORY_BASIS_FORBIDDEN"
DC1_QUERY_NOT_EPHEMERAL = "DC1_QUERY_NOT_EPHEMERAL"
DC1_QUERY_RESOLVED_TIME_FORBIDDEN = "DC1_QUERY_RESOLVED_TIME_FORBIDDEN"
DC1_INVALID_TEXT_SPAN = "DC1_INVALID_TEXT_SPAN"
DC1_EXPLICIT_EXPRESSION_MISMATCH = "DC1_EXPLICIT_EXPRESSION_MISMATCH"
DC1_SUBJECT_NOT_DREAM_SHARD = "DC1_SUBJECT_NOT_DREAM_SHARD"
DC1_BACKING_SUBJECT_NOT_DREAM_SHARD = "DC1_BACKING_SUBJECT_NOT_DREAM_SHARD"
DC1_BACKING_SHARD_SELF_REFERENCE = "DC1_BACKING_SHARD_SELF_REFERENCE"
DC1_MISSING_BASIS_REFERENCE = "DC1_MISSING_BASIS_REFERENCE"
DC1_RULE_IDENTITY_INCOMPLETE = "DC1_RULE_IDENTITY_INCOMPLETE"
DC1_INVALID_PREDECESSOR = "DC1_INVALID_PREDECESSOR"
DC1_PROVISIONAL_FIRST_STEP_FORBIDDEN = "DC1_PROVISIONAL_FIRST_STEP_FORBIDDEN"
DC1_PROVISIONAL_RATIONALE_REQUIRED = "DC1_PROVISIONAL_RATIONALE_REQUIRED"
DC1_LEGACY_ANCHOR_FIELD_FORBIDDEN = "DC1_LEGACY_ANCHOR_FIELD_FORBIDDEN"
DC1_PROPOSAL_ID_PAYLOAD_CONFLICT = "DC1_PROPOSAL_ID_PAYLOAD_CONFLICT"
DC1_CORTEX_ROOT_EQUALS_EVIDENCE_ROOT = "DC1_CORTEX_ROOT_EQUALS_EVIDENCE_ROOT"
DC1_RECEIPT_PROPOSAL_MISMATCH = "DC1_RECEIPT_PROPOSAL_MISMATCH"
DC1_ON_DISK_CONTRACT_VIOLATION = "DC1_ON_DISK_CONTRACT_VIOLATION"
DC1_QUERY_RELATIVE_EXPLICIT_SPAN_REQUIRED = "DC1_QUERY_RELATIVE_EXPLICIT_SPAN_REQUIRED"
DC1_DUPLICATE_CONFLICT_REFERENCE = "DC1_DUPLICATE_CONFLICT_REFERENCE"
DC1_CONFLICT_REFERENCE_NOT_EPISTEMIC_RECORD = "DC1_CONFLICT_REFERENCE_NOT_EPISTEMIC_RECORD"
DC1_RECEIPT_INPUT_SNAPSHOT_MISMATCH = "DC1_RECEIPT_INPUT_SNAPSHOT_MISMATCH"
DC1_RECEIPT_KIND_INVALID = "DC1_RECEIPT_KIND_INVALID"
DC1_RULE_IDENTITY_INCONSISTENT = "DC1_RULE_IDENTITY_INCONSISTENT"


@dataclass
class DC1Rejection(ValueError):
    """A deterministic DC1 rejection with machine-readable reason codes."""

    reason_codes: tuple[str, ...]
    detail: str

    def __str__(self) -> str:
        return f"{','.join(self.reason_codes)}: {self.detail}"


def reject(code: str, detail: str) -> None:
    raise DC1Rejection((code,), detail)


__all__ = [name for name in globals() if name.startswith("DC1_")] + ["DC1Rejection", "reject"]
