"""DF1 finite field assembly error codes."""

from __future__ import annotations

from dataclasses import dataclass


DF1_EMPTY_ADMISSION_SET = "DF1_EMPTY_ADMISSION_SET"
DF1_IMPLICIT_DISCOVERY_FORBIDDEN = "DF1_IMPLICIT_DISCOVERY_FORBIDDEN"
DF1_DUPLICATE_ADMISSION_ID = "DF1_DUPLICATE_ADMISSION_ID"
DF1_ADMISSION_FINGERPRINT_CONFLICT = "DF1_ADMISSION_FINGERPRINT_CONFLICT"
DF1_GEOMETRY_PROFILE_MISMATCH = "DF1_GEOMETRY_PROFILE_MISMATCH"
DF1_FIELD_POLICY_MISMATCH = "DF1_FIELD_POLICY_MISMATCH"
DF1_ADMISSION_REPLAY_INVALID = "DF1_ADMISSION_REPLAY_INVALID"
DF1_SHARD_NOT_FOUND = "DF1_SHARD_NOT_FOUND"
DF1_PROPOSAL_NOT_FOUND = "DF1_PROPOSAL_NOT_FOUND"
DF1_PROPOSAL_NOT_ACCEPTED = "DF1_PROPOSAL_NOT_ACCEPTED"
DF1_ADMISSION_BINDING_MISMATCH = "DF1_ADMISSION_BINDING_MISMATCH"
DF1_PROJECTION_FINGERPRINT_MISMATCH = "DF1_PROJECTION_FINGERPRINT_MISMATCH"
DF1_UNVERIFIED_CHART_LINK = "DF1_UNVERIFIED_CHART_LINK"
DF1_CHART_LINK_MANIFEST_INVALID = "DF1_CHART_LINK_MANIFEST_INVALID"
DF1_UNSUPPORTED_MUTABLE_INPUT = "DF1_UNSUPPORTED_MUTABLE_INPUT"
DF1_UNIVERSE_CONSTRUCTION_FAILED = "DF1_UNIVERSE_CONSTRUCTION_FAILED"


@dataclass
class DF1AssemblyError(ValueError):
    reason_code: str
    detail: str

    def __str__(self) -> str:
        return f"{self.reason_code}: {self.detail}"


def reject(code: str, detail: str) -> None:
    raise DF1AssemblyError(code, detail)


__all__ = [name for name in globals() if name.startswith("DF1_")] + ["DF1AssemblyError", "reject"]
